version: '3.8'
services:
  db:
    image: postgres:15
    container_name: erp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp_main
    volumes:
      - pgdata_erp:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - erpnet

volumes:
  pgdata_erp:
    external: true

networks:
  erpnet:
    external: true

